// src/app/pages/blocks/blocks.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BlockchainService, Block } from '../../services/blockchain.service';
import { I18nService } from '../../services/i18n.service';
import { CardComponent } from '../../components/ui/card/card.component';
import { BadgeComponent } from '../../components/ui/badge/badge.component';

@Component({
  selector: 'app-blocks',
  standalone: true,
  imports: [CommonModule, CardComponent, BadgeComponent],
  templateUrl: './blocks.component.html',
  styleUrls: ['./blocks.component.scss']
})
export class BlocksComponent implements OnInit {
  blocks: Block[] = [];

  constructor(
    private blockchainService: BlockchainService,
    public i18n: I18nService
  ) {}

  ngOnInit() {
    this.blockchainService.getBlocks().subscribe(blocks => {
      this.blocks = blocks;
    });
  }

  formatHash(hash: string): string {
    return `${hash.substring(0, 10)}...${hash.substring(hash.length - 8)}`;
  }

  formatAddress(address: string): string {
    return `${address.substring(0, 8)}...${address.substring(address.length - 6)}`;
  }

  formatTime(date: Date): string {
    const now = new Date();
    const diff = Math.floor((now.getTime() - date.getTime()) / 1000);
    
    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    return `${Math.floor(diff / 86400)}d ago`;
  }
}

<div class="page-container">
  <h1 class="page-title">{{ i18n.translate('blocks.title') }}</h1>

  <app-card>
    <div class="table-wrapper">
      <table class="data-table">
        <thead class="table-header">
          <tr>
            <th class="table-th">{{ i18n.translate('blocks.height') }}</th>
            <th class="table-th">{{ i18n.translate('blocks.hash') }}</th>
            <th class="table-th">{{ i18n.translate('blocks.timestamp') }}</th>
            <th class="table-th">{{ i18n.translate('blocks.txCount') }}</th>
            <th class="table-th">{{ i18n.translate('blocks.miner') }}</th>
          </tr>
        </thead>
        <tbody class="table-body">
          <tr *ngFor="let block of blocks" class="table-row">
            <td class="table-td">
              <span class="block-height">#{{ block.height }}</span>
            </td>
            <td class="table-td">
              <span class="hash-text">{{ formatHash(block.hash) }}</span>
            </td>
            <td class="table-td">
              <span class="time-text">{{ formatTime(block.timestamp) }}</span>
            </td>
            <td class="table-td">
              <app-badge variant="info">{{ block.txCount }}</app-badge>
            </td>
            <td class="table-td">
              <span class="address-text">{{ formatAddress(block.miner) }}</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </app-card>
</div>

// src/routes/blocks/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getBlocks, type Block } from '$lib/services/blockchain';
	import { translate } from '$lib/stores/i18n';
	import Card from '$lib/components/ui/Card.svelte';
	import ErrorCard from '$lib/components/ui/ErrorCard.svelte';
	import Badge from '$lib/components/ui/Badge.svelte';
	import SkeletonLoader from '$lib/components/ui/SkeletonLoader.svelte';
	import LiveTimestamp from '$lib/components/ui/LiveTimestamp.svelte';

	let blocks: Block[] = [];
	let loading = true;
	let error: string | null = null;
	$: t = $translate;

	onMount(async () => {
		try {
			blocks = await getBlocks();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load blocks';
		} finally {
			loading = false;
		}
	});

	function formatHash(hash: string): string {
		return `${hash.substring(0, 10)}...${hash.substring(hash.length - 8)}`;
	}

	function formatAddress(address: string): string {
		return `${address.substring(0, 8)}...${address.substring(address.length - 6)}`;
	}
</script>

<div class="page-container">
	<h1 class="page-title">{t('blocks.title')}</h1>

	<Card>
		<div class="table-wrapper">
			{#if loading}
				<SkeletonLoader>
					<div class="p-6 space-y-4">
						{#each Array(10) as _, i}
							<div class="flex gap-4">
								<div class="skeleton skeleton-text w-20"></div>
								<div class="skeleton skeleton-text flex-1"></div>
								<div class="skeleton skeleton-text w-24"></div>
								<div class="skeleton skeleton-text w-16"></div>
								<div class="skeleton skeleton-text w-32"></div>
							</div>
						{/each}
					</div>
				</SkeletonLoader>
			{:else if error}
				<ErrorCard title="Failed to load blocks" message={error} onRetry={() => window.location.reload()} />
			{:else}
				<table class="data-table">
						<thead class="table-header">
							<tr>
								<th class="table-th">{t('blocks.height')}</th>
								<th class="table-th">{t('blocks.hash')}</th>
								<th class="table-th">{t('blocks.timestamp')}</th>
								<th class="table-th">{t('blocks.txCount')}</th>
							</tr>
						</thead>
					<tbody class="table-body">
						{#each blocks as block}
							<tr class="table-row">
								<td class="table-td">
									<a href="/blocks/{block.hash}" class="block-height hover:text-primary-600">
										#{block.height}
									</a>
								</td>
								<td class="table-td">
									<a href="/blocks/{block.hash}" class="hash-text hover:text-primary-600">
										{formatHash(block.hash)}
									</a>
								</td>
								<td class="table-td">
									<LiveTimestamp timestamp={Math.floor(block.timestamp.getTime() / 1000)} className="time-text" />
								</td>
								<td class="table-td">
									<Badge variant="info">{block.txCount}</Badge>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			{/if}
		</div>
	</Card>
</div>

<style>
</style>
