// src/lib/components/Navbar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { currentLanguage, translate, type Language } from '$lib/stores/i18n';
	import { isDarkMode } from '$lib/stores/theme';
	import { globalSearch, getSearchResultPath } from '$lib/services/search';

	$: currentPath = $page.url.pathname;
	$: t = $translate;

	let searchQuery = '';
	let isSearching = false;
	let searchTimeout: ReturnType<typeof setTimeout> | null = null;

	function switchLanguage(lang: Language) {
		currentLanguage.setLanguage(lang);
	}

	function toggleTheme() {
		isDarkMode.toggle();
	}

	// Auto-search when query looks complete
	function handleInput() {
		// Clear previous timeout
		if (searchTimeout) {
			clearTimeout(searchTimeout);
		}

		const trimmed = searchQuery.trim();
		
		// Check if query looks like a complete ID
		const isAccountAddress = /^(-1|0):[a-fA-F0-9]{64}$/.test(trimmed);
		const isHash = /^[a-fA-F0-9]{64}$/.test(trimmed);
		
		if (isAccountAddress || isHash) {
			// Auto-search after 500ms of no typing
			searchTimeout = setTimeout(() => {
				handleSearch(new Event('submit'));
			}, 500);
		}
	}

	async function handleSearch(event: Event) {
		event.preventDefault();
		if (!searchQuery.trim() || isSearching) return;

		isSearching = true;
		try {
			const result = await globalSearch(searchQuery);
			if (result.found && result.results.length > 0) {
				// Navigate to the first result
				const path = getSearchResultPath(result.results[0]);
				await goto(path);
				searchQuery = ''; // Clear search after navigation
			} else {
				alert('No results found for: ' + searchQuery);
			}
		} catch (error) {
			console.error('Search error:', error);
			alert('Search failed. Please try again.');
		} finally {
			isSearching = false;
		}
	}
</script>

<nav class="bg-secondary border-b border-custom shadow-lg">
	<div class="container mx-auto px-4">
		<div class="flex items-center justify-between h-16">
			<!-- Logo -->
			<div class="flex-shrink-0">
				<a href="/" class="flex items-center">
					{#if $isDarkMode}
						<img src="/AN Logo - horizontal white.svg" alt="Acki Nacki" class="h-8" />
					{:else}
						<img src="/AN Logo - horizontal black.svg" alt="Acki Nacki" class="h-8" />
					{/if}
				</a>
			</div>

			<!-- Global Search Bar -->
			<div class="hidden lg:block flex-1 max-w-md mx-4">
				<form on:submit={handleSearch} class="relative">
					<input
						type="text"
						bind:value={searchQuery}
						on:input={handleInput}
						placeholder="address / msg / tx / block"
						disabled={isSearching}
						class="w-full px-4 py-2 pl-10 pr-10 rounded-lg border transition-all"
						style="background-color: var(--bg-secondary); color: var(--text-primary); border-color: var(--border-color);"
					/>
					<svg
						class="w-5 h-5 absolute left-3 top-1/2 transform -translate-y-1/2"
						style="color: var(--text-muted);"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
						/>
					</svg>
					{#if isSearching}
						<div class="absolute right-3 top-1/2 transform -translate-y-1/2">
							<svg class="animate-spin h-5 w-5 text-primary-600" viewBox="0 0 24 24">
								<circle
									class="opacity-25"
									cx="12"
									cy="12"
									r="10"
									stroke="currentColor"
									stroke-width="4"
									fill="none"
								/>
								<path
									class="opacity-75"
									fill="currentColor"
									d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
								/>
							</svg>
						</div>
					{/if}
				</form>
			</div>

			<!-- Navigation Links -->
			<div class="hidden md:flex items-center space-x-1">
				<a href="/blocks" class="nav-link" class:active={currentPath === '/blocks'}>
					{t('nav.blocks')}
				</a>
				<a href="/transactions" class="nav-link" class:active={currentPath === '/transactions'}>
					{t('nav.transactions')}
				</a>
				<a href="/messages" class="nav-link" class:active={currentPath === '/messages'}>
					{t('nav.messages')}
				</a>
				<a href="/contracts" class="nav-link" class:active={currentPath === '/contracts'}>
					{t('nav.contracts')}
				</a>
				<a href="/stats" class="nav-link" class:active={currentPath === '/stats'}>
					{t('nav.stats')}
				</a>
				<a href="/showcase" class="nav-link" class:active={currentPath === '/showcase'}>
					{t('nav.showcase')}
				</a>
			</div>

			<!-- Controls -->
			<div class="flex items-center space-x-4">
				<!-- Language Switcher -->
				<div class="flex items-center space-x-2">
					<button
						on:click={() => switchLanguage('en')}
						class="px-3 py-1 rounded text-sm transition-colors"
						class:bg-primary-600={$currentLanguage === 'en'}
						class:text-white={$currentLanguage === 'en'}
						class:text-secondary={$currentLanguage !== 'en'}
						class:hover:bg-tertiary={$currentLanguage !== 'en'}
					>
						EN
					</button>
					<button
						on:click={() => switchLanguage('ru')}
						class="px-3 py-1 rounded text-sm transition-colors"
						class:bg-primary-600={$currentLanguage === 'ru'}
						class:text-white={$currentLanguage === 'ru'}
						class:text-secondary={$currentLanguage !== 'ru'}
						class:hover:bg-tertiary={$currentLanguage !== 'ru'}
					>
						RU
					</button>
				</div>

				<!-- Theme Toggle -->
				<button
					on:click={toggleTheme}
					class="p-2 rounded-lg hover:bg-tertiary transition-colors text-secondary"
					aria-label="Toggle theme"
				>
					{#if $isDarkMode}
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
							/>
						</svg>
					{:else}
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
							/>
						</svg>
					{/if}
				</button>
			</div>
		</div>
	</div>
</nav>

// src/app/components/navbar/navbar.component.ts
import { Component, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { I18nService, Language } from '../../services/i18n.service';
import { ThemeService } from '../../services/theme.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  currentLang = computed(() => this.i18n.currentLang());
  isDarkMode = computed(() => this.themeService.isDark());

  constructor(
    public i18n: I18nService,
    private themeService: ThemeService
  ) {}

  switchLanguage(lang: Language) {
    this.i18n.setLanguage(lang);
    // Force component re-render
    window.location.reload();
  }

  toggleTheme() {
    this.themeService.toggleTheme();
  }
}

<nav class="bg-secondary border-b border-custom shadow-lg">
  <div class="container mx-auto px-4">
    <div class="flex items-center justify-between h-16">
      <!-- Logo -->
      <div class="flex-shrink-0">
        <a routerLink="/" class="flex items-center space-x-2">
          <div class="w-8 h-8 bg-gradient-to-br from-primary-500 to-primary-700 rounded-lg flex items-center justify-center">
            <span class="text-white font-bold text-lg">A</span>
          </div>
          <span class="text-xl font-bold text-primary">ACKI.live</span>
        </a>
      </div>

      <!-- Navigation Links -->
      <div class="hidden md:flex items-center space-x-1">
        <a routerLink="/blocks" 
           routerLinkActive="active"
           class="nav-link px-4 py-2 rounded-lg text-secondary hover:bg-tertiary transition-colors">
          {{ i18n.translate('nav.blocks') }}
        </a>
        <a routerLink="/transactions" 
           routerLinkActive="active"
           class="nav-link px-4 py-2 rounded-lg text-secondary hover:bg-tertiary transition-colors">
          {{ i18n.translate('nav.transactions') }}
        </a>
        <a routerLink="/messages" 
           routerLinkActive="active"
           class="nav-link px-4 py-2 rounded-lg text-secondary hover:bg-tertiary transition-colors">
          {{ i18n.translate('nav.messages') }}
        </a>
        <a routerLink="/contracts" 
           routerLinkActive="active"
           class="nav-link px-4 py-2 rounded-lg text-secondary hover:bg-tertiary transition-colors">
          {{ i18n.translate('nav.contracts') }}
        </a>
        <a routerLink="/stats" 
           routerLinkActive="active"
           class="nav-link px-4 py-2 rounded-lg text-secondary hover:bg-tertiary transition-colors">
          {{ i18n.translate('nav.stats') }}
        </a>
        <a routerLink="/showcase" 
           routerLinkActive="active"
           class="nav-link px-4 py-2 rounded-lg text-secondary hover:bg-tertiary transition-colors">
          {{ i18n.translate('nav.showcase') }}
        </a>
      </div>

      <!-- Controls -->
      <div class="flex items-center space-x-4">
        <!-- Language Switcher -->
        <div class="flex items-center space-x-2 bg-tertiary rounded-lg p-1">
          <button 
            (click)="switchLanguage('en')"
            [class.active-lang]="currentLang() === 'en'"
            class="lang-btn px-3 py-1 rounded-md text-sm font-medium transition-colors">
            EN
          </button>
          <button 
            (click)="switchLanguage('ru')"
            [class.active-lang]="currentLang() === 'ru'"
            class="lang-btn px-3 py-1 rounded-md text-sm font-medium transition-colors">
            RU
          </button>
        </div>

        <!-- Theme Toggle -->
        <button 
          (click)="toggleTheme()"
          class="p-2 rounded-lg bg-tertiary hover:bg-opacity-80 transition-colors"
          [attr.aria-label]="'Toggle theme'">
          <svg *ngIf="isDarkMode" class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" clip-rule="evenodd"></path>
          </svg>
          <svg *ngIf="!isDarkMode" class="w-5 h-5 text-gray-700" fill="currentColor" viewBox="0 0 20 20">
            <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</nav>
