// src/app/pages/transactions/transactions.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BlockchainService, Transaction } from '../../services/blockchain.service';
import { I18nService } from '../../services/i18n.service';
import { CardComponent } from '../../components/ui/card/card.component';
import { BadgeComponent, BadgeVariant } from '../../components/ui/badge/badge.component';

@Component({
  selector: 'app-transactions',
  standalone: true,
  imports: [CommonModule, CardComponent, BadgeComponent],
  templateUrl: './transactions.component.html',
  styleUrls: ['./transactions.component.scss']
})
export class TransactionsComponent implements OnInit {
  transactions: Transaction[] = [];

  constructor(
    private blockchainService: BlockchainService,
    public i18n: I18nService
  ) {}

  ngOnInit() {
    this.blockchainService.getTransactions().subscribe(txs => {
      this.transactions = txs;
    });
  }

  formatHash(hash: string): string {
    return `${hash.substring(0, 10)}...${hash.substring(hash.length - 8)}`;
  }

  formatAddress(address: string): string {
    return `${address.substring(0, 8)}...${address.substring(address.length - 6)}`;
  }

  formatTime(date: Date): string {
    const now = new Date();
    const diff = Math.floor((now.getTime() - date.getTime()) / 1000);
    
    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    return `${Math.floor(diff / 86400)}d ago`;
  }

  getStatusClass(status: string): BadgeVariant {
    switch (status) {
      case 'success': return 'success';
      case 'pending': return 'pending';
      case 'failed': return 'failed';
      default: return 'info';
    }
  }
}

<div class="page-container">
  <h1 class="page-title">{{ i18n.translate('transactions.title') }}</h1>

  <app-card>
    <div class="table-wrapper">
      <table class="data-table">
        <thead class="table-header">
          <tr>
            <th class="table-th">{{ i18n.translate('transactions.hash') }}</th>
            <th class="table-th">{{ i18n.translate('transactions.from') }}</th>
            <th class="table-th">{{ i18n.translate('transactions.to') }}</th>
            <th class="table-th">{{ i18n.translate('transactions.amount') }}</th>
            <th class="table-th">{{ i18n.translate('transactions.status') }}</th>
            <th class="table-th">{{ i18n.translate('transactions.time') }}</th>
          </tr>
        </thead>
        <tbody class="table-body">
          <tr *ngFor="let tx of transactions" class="table-row">
            <td class="table-td">
              <span class="hash-text">{{ formatHash(tx.hash) }}</span>
            </td>
            <td class="table-td">
              <span class="address-text">{{ formatAddress(tx.from) }}</span>
            </td>
            <td class="table-td">
              <span class="address-text">{{ formatAddress(tx.to) }}</span>
            </td>
            <td class="table-td">
              <span class="amount-text">{{ tx.amount.toFixed(4) }} ACKI</span>
            </td>
            <td class="table-td">
              <app-badge [variant]="getStatusClass(tx.status)">
                {{ i18n.translate('status.' + tx.status) }}
              </app-badge>
            </td>
            <td class="table-td">
              <span class="time-text">{{ formatTime(tx.timestamp) }}</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </app-card>
</div>

// src/routes/transactions/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getTransactions, type Transaction } from '$lib/services/blockchain';
	import { translate } from '$lib/stores/i18n';
	import Card from '$lib/components/ui/Card.svelte';
	import ErrorCard from '$lib/components/ui/ErrorCard.svelte';
	import Badge from '$lib/components/ui/Badge.svelte';
	import SkeletonLoader from '$lib/components/ui/SkeletonLoader.svelte';
	import LiveTimestamp from '$lib/components/ui/LiveTimestamp.svelte';

	let transactions: Transaction[] = [];
	let loading = true;
	let error: string | null = null;
	$: t = $translate;

	onMount(async () => {
		try {
			transactions = await getTransactions();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load transactions';
		} finally {
			loading = false;
		}
	});

	function formatHash(hash: string): string {
		return `${hash.substring(0, 10)}...${hash.substring(hash.length - 8)}`;
	}

	function formatAddress(address: string): string {
		return `${address.substring(0, 8)}...${address.substring(address.length - 6)}`;
	}

	function getStatusVariant(status: string): 'success' | 'info' | 'warning' | 'error' {
		if (status === 'success') return 'success';
		if (status === 'pending') return 'warning';
		return 'error';
	}
</script>

<div class="page-container">
	<h1 class="page-title">{t('transactions.title')}</h1>

	<Card>
		<div class="table-wrapper">
			{#if loading}
				<SkeletonLoader>
					<div class="p-6 space-y-4">
						{#each Array(10) as _, i}
							<div class="flex gap-4">
								<div class="skeleton skeleton-text w-24"></div>
								<div class="skeleton skeleton-text w-20"></div>
								<div class="skeleton skeleton-text w-20"></div>
								<div class="skeleton skeleton-text w-20"></div>
								<div class="skeleton skeleton-text w-16"></div>
								<div class="skeleton skeleton-text w-24"></div>
							</div>
						{/each}
					</div>
				</SkeletonLoader>
			{:else if error}
				<ErrorCard title="Failed to load transactions" message={error} onRetry={() => window.location.reload()} />
			{:else}
				<table class="data-table">
						<thead class="table-header">
							<tr>
								<th class="table-th">{t('transactions.hash')}</th>
								<th class="table-th">{t('transactions.from')}</th>
								<th class="table-th">{t('transactions.to')}</th>
								<th class="table-th">{t('transactions.amount')}</th>
								<th class="table-th">{t('transactions.status')}</th>
								<th class="table-th">{t('transactions.time')}</th>
							</tr>
						</thead>
					<tbody class="table-body">
						{#each transactions as tx}
							<tr class="table-row">
								<td class="table-td">
									<a href="/transactions/{tx.hash}" class="hash-text hover:text-primary-600">
										{formatHash(tx.hash)}
									</a>
								</td>
								<td class="table-td">
									<span class="address-text">{formatAddress(tx.from)}</span>
								</td>
								<td class="table-td">
									<span class="address-text">{formatAddress(tx.to)}</span>
								</td>
								<td class="table-td">
									<span class="font-semibold text-primary">{tx.amount.toFixed(4)}</span>
								</td>
								<td class="table-td">
									<Badge variant={getStatusVariant(tx.status)}>
										{t(`status.${tx.status}`)}
									</Badge>
								</td>
								<td class="table-td">
									<LiveTimestamp timestamp={Math.floor(tx.timestamp.getTime() / 1000)} className="time-text" />
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			{/if}
		</div>
	</Card>
</div>
